### ISSUE TITLE
Add starter project to the repo

### ISSUE THREAD

**Issue by JoeProgrammer88** [CPTC-CPW/GameProject#9]
We need to add a Unity project to the repo. I've been having issues with the GitHub for Unity extension, if you are as well we could use GitHub desktop or git command line (git CLI)

**Comment by AmyshaDixon** [comment]
I personally prefer GitHub desktop because I feel it is easier to use, but I am more than open to using command line as well; I would just need some help with it.

**Comment by AnMcCbusiness** [comment]
I use GitHub desktop for 90% of everything outside of VS, so that'll do.

**Comment by JoeProgrammer88** [comment]
@AnMcCbusiness Can you upload your complete example to his repo? The rest of us still need to follow the tutorial and then we can make improvements and enhancements from there

**Comment by AnMcCbusiness** [comment]
@JoeProgrammer88 I'd love to, but it seems GitHub Desktop is having a strange issue with the .PNG readme file and won't let me do any committing until that is resolved. I tried to fix the issue by trying out GitHub for Unity and it completely wiped my project somehow when creating a new branch. So, I don't really recommend GitHub for Unity at the moment. Fortunately, I have a backup. I'm not sure I can get around the strange .PNG file issue through GitHub Desktop as I cannot commit to the master branch because it is protected. Images attached: 
![githubdesktopissue](https://user-images.githubusercontent.com/29992008/48456912-a6c63e80-e775-11e8-9aa2-e7dded80d4f5.PNG)

**Comment by AmyshaDixon** [comment]
@AnMcCbusiness Can the PNG be converted into a JPEG or PDF? Or does the protection somehow get in the way? I am not sure if it is possible or if GitHub will allow either of those, but I thought I'd ask.

**Comment by JoeProgrammer88** [comment]
@AnMcCbusiness 
I did add PNG's to be under Git LFS meaning they should be handled as a binary file. I wonder if that is part of the problem? I'll read into that tonight. 
I could un-protect the master branch but I would like to avoid that if possible just to stick with our normal workflow of separate branches and pull requests. I'll experiment with that tonight too

**Comment by JoeProgrammer88** [comment]
GitHub for Unity is a lot better now (I can actually log in now 😃 )
Starter project with first iteration of battle system created in #11
